"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import SessionGenerator from "@/components/SessionGenerator";
import Navbar from "@/components/Navbar";

interface Question {
  _id: string;
  questionText: string;
  difficulty?: string;
}

interface User {
  name: string;
  email: string;
}

export default function Home() {
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [firstQuestion, setFirstQuestion] = useState<Question | null>(null);
  const [totalQuestions, setTotalQuestions] = useState<number>(0);
  const [user, setUser] = useState<User | null>(null);
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (token) {
      try {
        const payload = JSON.parse(atob(token.split('.')[1]));
        if (payload && (payload.name || payload.email)) {
          setUser({
            name: payload.name || 'User',
            email: payload.email || ''
          });
        } else {
          console.error("Invalid token payload");
          localStorage.removeItem("token");
        }
      } catch (error) {
        console.error("Invalid token");
        localStorage.removeItem("token");
      }
    }
  }, []);

  const onSessionCreated = (sessionId: string, question: Question, totalQuestions: number) => {
    setSessionId(sessionId);
    setFirstQuestion(question);
    setTotalQuestions(totalQuestions);
  };

  const features = [
    {
      icon: "🤖",
      title: "AI-Powered Questions",
      description: "Get unique, creative questions generated by advanced AI that adapts to your skill level and preferences."
    },
    {
      icon: "📊",
      title: "Performance Analytics",
      description: "Track your progress with detailed analytics and insights to identify areas for improvement."
    },
    {
      icon: "🎯",
      title: "Personalized Practice",
      description: "Customize your practice sessions with specific topics, difficulty levels, and question types."
    },
    {
      icon: "💡",
      title: "Instant Feedback",
      description: "Receive immediate feedback on your answers to learn and improve in real-time."
    },
    {
      icon: "📱",
      title: "Mobile Friendly",
      description: "Practice anywhere, anytime with our responsive design that works on all devices."
    },
    {
      icon: "🔒",
      title: "Secure & Private",
      description: "Your data is encrypted and secure. We respect your privacy and never share your information."
    }
  ];

  const testimonials = [
    {
      name: "Sarah Chen",
      role: "Software Engineer at Google",
      content: "This platform helped me land my dream job! The AI questions were incredibly realistic and challenging.",
      avatar: "SC"
    },
    {
      name: "Michael Rodriguez",
      role: "Full Stack Developer",
      content: "The personalized feedback was game-changing. I improved my interview skills significantly in just two weeks.",
      avatar: "MR"
    },
    {
      name: "Emily Johnson",
      role: "Data Scientist at Meta",
      content: "The variety of questions kept me engaged. Each session felt fresh and helped me prepare for different scenarios.",
      avatar: "EJ"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <Navbar />

      {!sessionId ? (
        <>
          {/* Hero Section */}
          <section className="relative overflow-hidden">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
              <div className="text-center">
                <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
                  Master Your Next
                  <span className="bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent"> Interview</span>
                </h1>
                <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
                  Prepare with confidence using AI-powered interview questions tailored to your skills and goals.
                  Join thousands of developers who've landed their dream jobs.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                  {user ? (
                    <button
                      onClick={() => router.push("/dashboard")}
                      className="px-8 py-4 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg text-lg font-medium hover:from-blue-600 hover:to-purple-700 transition-all duration-200 shadow-lg hover:shadow-xl"
                    >
                      Go to Dashboard
                    </button>
                  ) : (
                    <button
                      onClick={() => router.push("/auth")}
                      className="px-8 py-4 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg text-lg font-medium hover:from-blue-600 hover:to-purple-700 transition-all duration-200 shadow-lg hover:shadow-xl"
                    >
                      Get Started Free
                    </button>
                  )}
                  <button
                    onClick={() => document.getElementById('session-generator')?.scrollIntoView({ behavior: 'smooth' })}
                    className="px-8 py-4 border-2 border-gray-300 text-gray-700 rounded-lg text-lg font-medium hover:border-gray-400 hover:bg-gray-50 transition-all duration-200"
                  >
                    Try Demo
                  </button>
                </div>
              </div>
            </div>

            {/* Background decoration */}
            <div className="absolute top-0 left-0 w-full h-full overflow-hidden -z-10">
              <div className="absolute top-20 left-10 w-20 h-20 bg-blue-200 rounded-full opacity-20 animate-pulse"></div>
              <div className="absolute top-40 right-20 w-32 h-32 bg-purple-200 rounded-full opacity-20 animate-pulse delay-1000"></div>
              <div className="absolute bottom-20 left-1/4 w-16 h-16 bg-indigo-200 rounded-full opacity-20 animate-pulse delay-2000"></div>
            </div>
          </section>

          {/* Features Section */}
          <section className="py-20 bg-white">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center mb-16">
                <h2 className="text-4xl font-bold text-gray-900 mb-4">Why Choose Our Platform?</h2>
                <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                  We combine cutting-edge AI technology with proven interview preparation methods
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {features.map((feature, index) => (
                  <div key={index} className="bg-gray-50 rounded-xl p-6 hover:shadow-lg transition-shadow duration-200">
                    <div className="text-4xl mb-4">{feature.icon}</div>
                    <h3 className="text-xl font-semibold text-gray-900 mb-2">{feature.title}</h3>
                    <p className="text-gray-600">{feature.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* Session Generator Section */}
          <section id="session-generator" className="py-20">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center mb-12">
                <h2 className="text-4xl font-bold text-gray-900 mb-4">Start Your Practice Session</h2>
                <p className="text-xl text-gray-600">
                  Create a personalized interview session in just a few clicks
                </p>
              </div>

              <SessionGenerator onSessionCreated={onSessionCreated} />
            </div>
          </section>

          {/* Testimonials Section */}
          <section className="py-20 bg-white">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center mb-16">
                <h2 className="text-4xl font-bold text-gray-900 mb-4">Success Stories</h2>
                <p className="text-xl text-gray-600">
                  See how our platform has helped developers land their dream jobs
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {testimonials.map((testimonial, index) => (
                  <div key={index} className="bg-gray-50 rounded-xl p-6">
                    <div className="flex items-center mb-4">
                      <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
                        {testimonial.avatar}
                      </div>
                      <div className="ml-4">
                        <h4 className="font-semibold text-gray-900">{testimonial.name}</h4>
                        <p className="text-sm text-gray-600">{testimonial.role}</p>
                      </div>
                    </div>
                    <p className="text-gray-700 italic">"{testimonial.content}"</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* CTA Section */}
          <section className="py-20 bg-gradient-to-r from-blue-500 to-purple-600">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
              <h2 className="text-4xl font-bold text-white mb-4">Ready to Ace Your Interview?</h2>
              <p className="text-xl text-blue-100 mb-8">
                Join thousands of successful candidates who prepared with our AI-powered platform
              </p>
              {!user && (
                <button
                  onClick={() => router.push("/auth")}
                  className="px-8 py-4 bg-white text-blue-600 rounded-lg text-lg font-medium hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl"
                >
                  Start Free Trial
                </button>
              )}
            </div>
          </section>
        </>
      ) : firstQuestion ? (
        <InterviewWithSession
          sessionId={sessionId}
          firstQuestion={firstQuestion}
          totalQuestions={totalQuestions}
          onExit={() => {
            setSessionId(null);
            setFirstQuestion(null);
            setTotalQuestions(0);
          }}
        />
      ) : null}
    </div>
  );
}

// Enhanced Interview Session Component
function InterviewWithSession({
  sessionId,
  firstQuestion,
  totalQuestions,
  onExit,
}: {
  sessionId: string;
  firstQuestion: Question;
  totalQuestions: number;
  onExit: () => void;
}) {
  const [currentQuestion, setCurrentQuestion] = useState<Question>(firstQuestion);
  const [answerText, setAnswerText] = useState("");
  const [completed, setCompleted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(1);

  const handleSubmitAnswer = async () => {
    if (!answerText.trim()) {
      setError("Please enter your answer");
      return;
    }
    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/interview/answer", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sessionId,
          questionId: currentQuestion._id,
          answerText,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Failed to save answer");
      } else {
        setAnswerText("");
        if (data.completed) {
          setCompleted(true);
        } else if (data.nextQuestion) {
          setCurrentQuestion(data.nextQuestion);
          setCurrentQuestionIndex(prev => prev + 1);
        }
      }
    } catch {
      setError("Unexpected error occurred");
    } finally {
      setLoading(false);
    }
  };

  if (completed) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 py-20">
        <div className="max-w-2xl mx-auto px-4 text-center">
          <div className="bg-white rounded-2xl shadow-xl p-8">
            <div className="text-6xl mb-6">🎉</div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Interview Completed!</h2>
            <p className="text-gray-600 mb-8">
              Congratulations! You've successfully completed your interview session.
              Your responses have been saved and you can review them in your dashboard.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button
                onClick={onExit}
                className="px-6 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg hover:from-blue-600 hover:to-purple-700 transition-all duration-200"
              >
                Start New Session
              </button>
              <button
                onClick={() => window.location.href = "/dashboard"}
                className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
              >
                View Dashboard
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          {/* Progress Bar */}
          <div className="mb-8">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-gray-700">Progress</span>
              <span className="text-sm text-gray-500">{currentQuestionIndex} of {totalQuestions}</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-2">
              <div
                className="bg-gradient-to-r from-blue-500 to-purple-600 h-2 rounded-full transition-all duration-300"
                style={{ width: `${(currentQuestionIndex / totalQuestions) * 100}%` }}
              ></div>
            </div>
          </div>

          {/* Question */}
          <div className="mb-8">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-sm">
                Q
              </div>
              <div className="flex-1">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">
                  {currentQuestion.questionText}
                </h2>
                {currentQuestion.difficulty && (
                  <span className={`inline-block px-3 py-1 rounded-full text-xs font-medium ${currentQuestion.difficulty === 'easy' ? 'bg-green-100 text-green-800' :
                    currentQuestion.difficulty === 'intermediate' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-red-100 text-red-800'
                    }`}>
                    {currentQuestion.difficulty.charAt(0).toUpperCase() + currentQuestion.difficulty.slice(1)}
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Answer Input */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Your Answer:
            </label>
            <textarea
              rows={8}
              value={answerText}
              onChange={(e) => setAnswerText(e.target.value)}
              placeholder="Type your detailed answer here... Be specific and provide examples where possible."
              disabled={loading}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
            />
            <div className="flex justify-between items-center mt-2">
              <span className="text-xs text-gray-500">
                {answerText.length} characters
              </span>
              <span className="text-xs text-gray-500">
                Tip: Aim for detailed, structured responses
              </span>
            </div>
          </div>

          {error && (
            <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-red-800 text-sm">{error}</p>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex justify-between items-center">
            <button
              onClick={onExit}
              className="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors"
            >
              Exit Session
            </button>

            <div className="flex space-x-4">
              <button
                onClick={() => setAnswerText("")}
                disabled={loading || !answerText.trim()}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Clear
              </button>
              <button
                onClick={handleSubmitAnswer}
                disabled={loading || !answerText.trim()}
                className="px-6 py-2 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg hover:from-blue-600 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200"
              >
                {loading ? (
                  <div className="flex items-center">
                    <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Submitting...
                  </div>
                ) : (
                  currentQuestionIndex === totalQuestions ? "Finish Interview" : "Next Question"
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
